#!/bin/sh

# This shell script is called automatically at the end of each push operation.
#
# 1. Create the db if it doesn't exist.
# 2. Sync the db.
# 3. Create a default admin user.
# 4. Ensure media and static directories exist...
# 5. ...and collect static media.
# 6. Install crontab job for search index updating

#python createdb.py
python manage.py syncdb --noinput
python mkadmin.py
mkdir -p /home/dotcloud/data/media
mkdir -p /home/dotcloud/volatile/static
ln -sf /home/dotcloud/volatile/static /home/dotcloud/static
python manage.py collectstatic --noinput --verbosity=0
